version: "3.8"

services:
  client:
    container_name: cert-app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - cert-app-network
    # env_file:

networks:
  cert-app-network:
    name: cert-app-network
    driver: bridge
